# Generated by Django 2.1.3 on 2018-12-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BodhiAI_Blog_App', '0007_auto_20181208_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Image',
            field=models.ImageField(blank=True, default='static/chemical.png.', upload_to='static'),
        ),
    ]
