# Generated by Django 2.1.3 on 2018-12-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BodhiAI_Blog_App', '0008_auto_20181208_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='Image',
        ),
        migrations.AddField(
            model_name='blog',
            name='link_url',
            field=models.URLField(null=True),
        ),
    ]
