# Generated by Django 2.1.3 on 2018-12-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BodhiAI_Blog_App', '0010_auto_20181208_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='blog',
            name='link1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='link2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='link3',
            field=models.URLField(blank=True, null=True),
        ),
    ]
