# Generated by Django 2.1.3 on 2018-12-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BodhiAI_Blog_App', '0011_auto_20181212_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
