# Generated by Django 2.1.3 on 2018-12-18 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BodhiAI_Blog_App', '0021_auto_20181218_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='BodhiAI_Blog_App.comment'),
        ),
    ]
