# Generated by Django 2.1.3 on 2018-12-18 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BodhiAI_Blog_App', '0022_auto_20181218_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
