# Generated by Django 2.1.3 on 2018-12-19 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BodhiAI_Blog_App', '0024_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
