# Generated by Django 2.1.3 on 2018-12-19 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BodhiAI_Blog_App', '0025_auto_20181219_0641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodytext', models.TextField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(default='0.0.0.0')),
                ('user_name', models.CharField(default='anonymous', max_length=50)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='BodhiAI_Blog_App.Blog')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
