# Generated by Django 2.1.3 on 2018-12-19 02:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BodhiAI_Blog_App', '0027_auto_20181219_0703'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tweet',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
    ]
