# Generated by Django 2.1.3 on 2018-12-19 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BodhiAI_Blog_App', '0029_blog_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_by',
            field=models.ForeignKey(default='BodhiAI', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
