# Generated by Django 2.1.3 on 2018-12-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BodhiAI_Blog_App', '0031_auto_20181219_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=140),
        ),
    ]
